version: '3.8'
services:
  postgres-db:
    image: postgres:16
    container_name: poc-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pocdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_envers_data:/var/lib/postgresql/data

volumes:
  postgres_envers_data: